apiVersion: v1
kind: Secret
metadata:
  name: cck-secrets
  namespace: kube-system
type: Opaque
data:
  access_key_id: '*'
  access_key_secret: '*'
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cds-properties
  namespace: kube-system
data:
  k8s_cluster_id: ''
  site_id: ''
  site_name: ''
  oversea: ''
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cds-monitor-transfer
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      cdsapp: cds-monitor-transfer
  template:
    metadata:
      labels:
        cdsapp: cds-monitor-transfer
    spec:
      containers:
        - name: cds-monitor-transfer
          #image: registry-bj.capitalonline.net/cck/web_app:1.0
          image: capitalonline/web_app:1.0
          ports:
            - containerPort: 6666
              protocol: TCP
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "100m"
          volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /secret
            name: secret
      nodeSelector:
        node-role.kubernetes.io/master: ""
        node-role.kubernetes.io/infra: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - effect: NoSchedule
        key: node-role.cck.net/infra
      volumes:
        - name: secret
          secret:
            secretName: cck-secrets
        - name: config
          configMap:
            name: cds-properties
        
---

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: cds-monitor-transfer
  name: cds-monitor-transfer
  namespace: kube-system
spec:
  ports:
    - port: 6666
      targetPort: 6666
  selector:
    cdsapp: cds-monitor-transfer