apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    alertmanager: main
  name: main
  namespace: monitoring
spec:
  tolerations:
  - key: "node-role.kubernetes.io/master"
    effect: "NoSchedule"
  baseImage: registry-bj.capitalonline.net/cck/prometheus/alertmanager
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
    node.cck.net/role.infra: "True"
  replicas: 3
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: alertmanager-main
  version: v0.18.0
